name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    env:
      USER:  ${{ secrets.DOCKER_USER }}
      TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      REPO:  ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u "$USER" -p "$TOKEN"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$REPO":latest
    - name: Push Docker image
      run: docker push "$REPO"
  
  deploy:
    name: Call the deploy hook
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
    - name: Call the deploy hook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK }}
